language: node_js
node_js:
  - lts/*
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm install
  - npm run cypress:verify
script:
  - npm run build
  - npm run dev:test &
  - npm run cypress:run -- --record
  - kill $(jobs -p) || true
