language: javascript
cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cypress:verify
script:
  - npm run dev:test &
  - npm run cypress:run -- --record
  - kill $(jobs -p) || true
