version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.10.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}
            - npm-v1-
            - cypress-v1-{{ arch }}
            - cypress-v1-

      - run:
          name: Install Dependencies
          command: npm ci

      - run:
          name: Install Cypress
          command: npm install cypress@13.6.1

      - run:
          name: Install Cypress binaries ( forced )
          command: npx cypress install --force

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/Cypress
          key: npm-cypress-v1-{{ checksum "package-lock.json" }}-{{ arch }}

      - run:
          name: Build
          command: npm run build

      - run:
          name: Start Live Server
          command: npm run dev:test & sleep 5

      - run:
          name: Run Cypress Tests
          command: npm run cypress:run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
