version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.10.0

    steps:
      - checkout
      
      - run:
          name: Install Dependencies
          command: npm ci

      - run:
          name: Build
          command: npm run build

      - run:
          name: Start Live Server
          command: npm run dev:test & sleep 5

      - run:
          name: Run Cypress Tests
          command: npm run cypress:run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
